#!/usr/bin/env python3
"""Analyze N-of-1 CSV data and generate a Markdown report.

Example:
    python analyze.py --data ~/my_nof1/data.csv --out ~/my_nof1/report.md
"""

import argparse
import csv
import statistics
from collections import defaultdict
from datetime import datetime
from pathlib import Path


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        return list(reader)


def parse_numeric(value: str) -> float | None:
    try:
        return float(value)
    except (ValueError, TypeError):
        return None


def summarize(rows: list[dict[str, str]]) -> tuple[dict, list[str]]:
    """Compute summary statistics by phase for numeric columns."""
    numeric_keys = set()
    for row in rows:
        for key, value in row.items():
            if key in ("timestamp", "phase", "note", "date", "time"):
                continue
            if parse_numeric(value) is not None:
                numeric_keys.add(key)

    by_phase: dict[str, dict[str, list[float]]] = defaultdict(
        lambda: defaultdict(list)
    )

    for row in rows:
        phase = row.get("phase", "unknown")
        for key in numeric_keys:
            num_value = parse_numeric(row.get(key, ""))
            if num_value is not None:
                by_phase[phase][key].append(num_value)

    summary: dict[str, dict[str, dict[str, float | int]]] = {}
    for phase, vars_data in by_phase.items():
        summary[phase] = {}
        for var, values in vars_data.items():
            summary[phase][var] = {
                "n": len(values),
                "mean": round(statistics.mean(values), 2),
                "median": round(statistics.median(values), 2),
                "min": round(min(values), 2),
                "max": round(max(values), 2),
                "stdev": round(statistics.stdev(values), 2) if len(values) > 1 else 0.0,
            }

    return summary, sorted(numeric_keys)


def effect_size(baseline_mean: float, intervention_mean: float) -> float:
    return round(intervention_mean - baseline_mean, 2)


def generate_report(rows: list[dict[str, str]], summary: dict[str, dict[str, dict[str, float | int]]], variables: list[str]) -> str:
    lines = [
        "# N-of-1 Analysis Report",
        "",
        f"Generated: {datetime.now().isoformat()}",
        f"Total observations: {len(rows)}",
        "",
        "## Summary by Phase",
        "",
    ]

    for phase in ["baseline", "intervention", "withdrawal", "follow_up", "unknown"]:
        if phase not in summary:
            continue
        lines.append(f"### {phase}")
        lines.append("")
        lines.append("| Variable | n | Mean | Median | Min | Max | Stdev |")
        lines.append("|----------|---|------|--------|-----|-----|-------|")
        for var in variables:
            stats = summary[phase].get(var, {})
            if stats:
                lines.append(
                    f"| {var} | {stats['n']} | {stats['mean']} | {stats['median']} | "
                    f"{stats['min']} | {stats['max']} | {stats['stdev']} |"
                )
        lines.append("")

    if "baseline" in summary and "intervention" in summary:
        lines.append("## Baseline vs. Intervention Effect Sizes")
        lines.append("")
        lines.append("| Variable | Baseline Mean | Intervention Mean | Difference |")
        lines.append("|----------|--------------|-------------------|------------|")
        for var in variables:
            b = summary["baseline"].get(var, {}).get("mean")
            i = summary["intervention"].get(var, {}).get("mean")
            if b is not None and i is not None:
                diff = effect_size(b, i)
                lines.append(f"| {var} | {b} | {i} | {diff:+} |")
        lines.append("")

    lines.append("## Raw Data")
    lines.append("")
    lines.append("| # | Timestamp | Phase | " + " | ".join(variables) + " | Note |")
    header_sep = "|---|-----------|-------|" + "|".join(["---"] * len(variables)) + "|------|"
    lines.append(header_sep)
    for idx, row in enumerate(rows, 1):
        vals = [row.get(v, "") for v in variables]
        note = row.get("note", "").replace("|", ",")
        lines.append(
            f"| {idx} | {row.get('timestamp', '')} | {row.get('phase', '')} | "
            + " | ".join(vals) + f" | {note} |"
        )
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Report generated by Project Dao.Science N-of-1 toolkit.*")
    lines.append("")
    lines.append(
        "> **Caution**: N-of-1 findings apply only to the individual who collected the data. "
        "Do not generalize to others without further study."
    )

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze N-of-1 CSV data.")
    parser.add_argument("--data", required=True, help="Path to data.csv")
    parser.add_argument("--out", required=True, help="Path to output Markdown report")
    args = parser.parse_args()

    data_path = Path(args.data).expanduser()
    out_path = Path(args.out).expanduser()

    if not data_path.exists():
        raise FileNotFoundError(f"Data file not found: {data_path}")

    rows = load_csv(data_path)
    summary, variables = summarize(rows)

    report = generate_report(rows, summary, variables)
    out_path.write_text(report, encoding="utf-8")

    print(f"Report written to {out_path}")
    print(f"  Observations: {len(rows)}")
    print(f"  Numeric variables: {', '.join(variables)}")
    print(f"  Phases: {', '.join(summary.keys())}")


if __name__ == "__main__":
    main()
